-- HOSPITAL DESCRIPTIVE COMPARISON QUERIES (MySQL)
   use Medical;

/* How many patients of each gender exist, and what is their average age? */
SELECT 
    Gender,
    COUNT(*) AS total_patients,
    ROUND(AVG(Age), 2) AS avg_age
FROM patients
GROUP BY Gender;

/* How do departments differ by number of doctors, salary, and experience? */
SELECT 
    Department,
    COUNT(*) AS total_doctors,
    ROUND(AVG(Salary), 2) AS avg_salary,
    ROUND(AVG(Years_Experience), 2) AS avg_experience
FROM doctors
GROUP BY Department;
select * from doctors;
/* What are the averages of wait time and duration for each appointment type? */
SELECT 
    reason,
    COUNT(*) AS total_appointments,
    ROUND(AVG(Time), 2) AS avg_wait_time
FROM appointments
GROUP BY Reason;
select * from appointments;
/* How does each procedure type (MRI, X-Ray, Blood Test) perform by cost and duration? */
SELECT 
    Proced_ure,
    COUNT(*) AS total_treatments,
    ROUND(AVG(Cost), 2) AS avg_cost,
    ROUND(AVG(Duration), 2) AS avg_duration
FROM treatments
GROUP BY Proced_ure;

/* Which medicines are prescribed most often, and what is their average dosage? */
SELECT 
    Medicine_Name,
    COUNT(*) AS total_prescriptions,
    ROUND(AVG(Dosage), 2) AS avg_dosage
FROM prescriptions
GROUP BY Medicine_Name
ORDER BY total_prescriptions DESC
LIMIT 10;

/* Which payment methods contribute most to total revenue and discount usage? */
SELECT 
    Payment_Method,
    COUNT(*) AS total_bills,
    ROUND(SUM(Total), 2) AS total_revenue,
    ROUND(AVG(Discount), 2) AS avg_discount
FROM billing
GROUP BY Payment_Method;

/* How do surgery types compare by average cost and duration? */
SELECT 
    Type,
    COUNT(*) AS total_surgeries,
    ROUND(AVG(Cost), 2) AS avg_cost,
    ROUND(AVG(Duration), 2) AS avg_duration
FROM surgeries
GROUP BY Type;
select * from surgeries;
/* How many doctors are assigned to each shift, and what’s the average salary? */
SELECT 
    Shift,
    COUNT(Doctor_ID) AS total_doctors,
    ROUND(AVG(Salary), 2) AS avg_salary
FROM doctors
GROUP BY Shift;

/* How does patient gender affect hospital revenue and average billing amount? */
SELECT 
    p.Gender,
    ROUND(SUM(b.Total), 2) AS total_revenue,
    ROUND(AVG(b.Total), 2) AS avg_bill
FROM billing b
JOIN patients p ON b.Patient_ID = p.Patient_ID
GROUP BY p.Gender;

/* How do doctor experience levels affect their average salary? */
SELECT 
    CASE 
        WHEN Years_Experience < 5 THEN 'Junior'
        WHEN Years_Experience BETWEEN 5 AND 15 THEN 'Mid-Level'
        ELSE 'Senior'
    END AS Experience_Level,
    COUNT(*) AS total_doctors,
    ROUND(AVG(Salary), 2) AS avg_salary
FROM doctors
GROUP BY Experience_Level;

/* How does appointment volume vary across patient age groups? */
SELECT 
    CASE 
        WHEN Age < 18 THEN 'Under 18'
        WHEN Age BETWEEN 18 AND 35 THEN '18-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        WHEN Age BETWEEN 51 AND 65 THEN '51-65'
        ELSE '65+'
    END AS Age_Group,
    COUNT(a.Appointment_ID) AS total_appointments
FROM patients p
JOIN appointments a ON p.Patient_ID = a.Patient_ID
GROUP BY Age_Group;

/* Which departments generate the most billing revenue? */
SELECT 
    d.Department,
    ROUND(SUM(b.Total), 2) AS total_revenue,
    COUNT(b.Bill_ID) AS total_bills
FROM doctors d
JOIN appointments a ON d.Doctor_ID = a.Doctor_ID
JOIN billing b ON a.Appointment_ID = b.Appointment_ID
GROUP BY d.Department;
select * from appointments;
select * from billing;
/* How many treatments has each doctor performed and at what average cost? */
SELECT 
    t.Doctor_ID,
    COUNT(t.Treatment_ID) AS total_treatments,
    ROUND(AVG(t.Cost), 2) AS avg_treatment_cost
FROM treatments t
GROUP BY t.Doctor_ID;

/* What is the average waiting time per department? */
SELECT 
    d.Department,
    ROUND(AVG(a.Time), 2) AS avg_wait_time
FROM appointments a
JOIN doctors d ON a.Doctor_ID = d.Doctor_ID
GROUP BY d.Department;

/* How do doctors’ experience levels affect surgery frequency and cost? */
SELECT 
    CASE 
        WHEN d.Years_Experience < 5 THEN 'Junior'
        WHEN d.Years_Experience BETWEEN 5 AND 15 THEN 'Mid-Level'
        ELSE 'Senior'
    END AS Experience_Level,
    COUNT(s.Surgery_ID) AS total_surgeries,
    ROUND(AVG(s.Cost), 2) AS avg_surgery_cost
FROM surgeries s
JOIN doctors d ON s.Doctor_ID = d.Doctor_ID
GROUP BY Experience_Level;

/* How many prescriptions has each doctor issued? */
SELECT 
    pr.Doctor_ID,
    COUNT(pr.Prescription_ID) AS total_prescriptions
FROM prescriptions pr
GROUP BY pr.Doctor_ID;

/* What is the total revenue generated by each payment method? */
SELECT 
    Payment_Method,
    ROUND(SUM(Total), 2) AS total_revenue,
    COUNT(*) AS total_bills
FROM billing
GROUP BY Payment_Method;

/* Which Blood_group have the most patients and what is their average age? */
SELECT 
    Blood_group,
    COUNT(Patient_ID) AS total_patients,
    ROUND(AVG(Age), 2) AS avg_age
FROM patients
GROUP BY Blood_group
ORDER BY total_patients DESC;
select * from patients;
/* Which procedure type has the highest average cost? */
SELECT 
    Proced_ure,
    ROUND(AVG(Cost), 2) AS avg_cost
FROM treatments
GROUP BY Proced_ure
ORDER BY avg_cost DESC;

/* Which day of the week has the most appointments? */
SELECT 
    DAYNAME(STR_TO_DATE(Date, '%m/%d/%Y')) AS Day_Name,
    COUNT(Appointment_ID) AS total_appointments
FROM appointments
GROUP BY Day_Name
ORDER BY FIELD(Day_Name, 'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday');
select * from Appointments;
/* What is the average billing amount for each doctor? */
SELECT 
    d.Doctor_ID,
    ROUND(AVG(b.Total), 2) AS avg_bill
FROM billing b
JOIN appointments a ON b.Appointment_ID = a.Appointment_ID
JOIN doctors d ON a.Doctor_ID = d.Doctor_ID
GROUP BY d.Doctor_ID;

/* How do surgery costs vary by surgery type? */
SELECT 
    Type,
    ROUND(AVG(Cost), 2) AS avg_cost,
    COUNT(Surgery_ID) AS total_surgeries
FROM surgeries
GROUP BY Type;

/* How many doctors work per shift? */
SELECT 
    Shift,
    COUNT(Doctor_ID) AS total_doctors
FROM doctors
GROUP BY Shift;

/* How does average billing differ across patient age groups? */
SELECT 
    CASE 
        WHEN Age < 18 THEN 'Under 18'
        WHEN Age BETWEEN 18 AND 35 THEN '18-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        WHEN Age BETWEEN 51 AND 65 THEN '51-65'
        ELSE '65+'
    END AS Age_Group,
    ROUND(AVG(b.Total), 2) AS avg_bill
FROM patients p
JOIN billing b ON p.Patient_ID = b.Patient_ID
GROUP BY Age_Group;

/* What are the top prescribed medicines overall? */
SELECT 
    Medicine_Name,
    COUNT(*) AS total_times_prescribed
FROM prescriptions
GROUP BY Medicine_Name
ORDER BY total_times_prescribed DESC
LIMIT 10;

/* How does treatment cost differ by patient gender? */
SELECT 
    p.Gender,
    ROUND(AVG(t.Cost), 2) AS avg_treatment_cost
FROM treatments t
JOIN patients p ON t.Patient_ID = p.Patient_ID
GROUP BY p.Gender;

/* How long do surgeries take in each department on average? */
SELECT 
    d.Department,
    ROUND(AVG(s.Duration), 2) AS avg_duration
FROM surgeries s
JOIN doctors d ON s.Doctor_ID = d.Doctor_ID
GROUP BY d.Department;

/* How do appointment volumes differ by doctor experience level? */
SELECT 
    CASE 
        WHEN d.Years_Experience < 5 THEN 'Junior'
        WHEN d.Years_Experience BETWEEN 5 AND 15 THEN 'Mid-Level'
        ELSE 'Senior'
    END AS Experience_Level,
    COUNT(a.Appointment_ID) AS total_appointments
FROM appointments a
JOIN doctors d ON a.Doctor_ID = d.Doctor_ID
GROUP BY Experience_Level;

/* Average billing vs. waiting time (days) */
SELECT 
    CASE 
        WHEN DATEDIFF(t.Date, a.Date) <= 2 THEN 'Short Wait'
        WHEN DATEDIFF(t.Date, a.Date) <= 5 THEN 'Moderate Wait'
        ELSE 'Long Wait'
    END AS Wait_Category,
    ROUND(AVG(b.Total), 2) AS Avg_Billing
FROM appointments a
JOIN treatments t ON a.Patient_ID = t.Patient_ID
JOIN billing b ON b.Patient_ID = a.Patient_ID
GROUP BY Wait_Category;
